"""Add icon_name column to ActivityGroup

Revision ID: 12367b853605
Revises: 
Create Date: 2025-02-18 23:12:20.717248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12367b853605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_group', schema=None) as batch_op:
        batch_op.drop_column('icon_name')

    # ### end Alembic commands ###
