"""Remove unique constraint from client_id in activity_group

Revision ID: 1796ff66d4c6
Revises: 55c469036df7
Create Date: 2025-03-04 12:35:44.120449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1796ff66d4c6'
down_revision = '55c469036df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_group', schema=None) as batch_op:
        batch_op.drop_constraint('uq_activity_group_client_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_group', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_activity_group_client_id', ['client_id'])

    # ### end Alembic commands ###
