"""Add icon_color column to ActivityGroup

Revision ID: 30e481566aec
Revises: 12367b853605
Create Date: 2025-02-18 23:27:06.624099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e481566aec'
down_revision = '12367b853605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_color', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_group', schema=None) as batch_op:
        batch_op.drop_column('icon_color')

    # ### end Alembic commands ###
