"""Add Tag model and activity_tags table

Revision ID: 55c469036df7
Revises: 8bdf35c902e3
Create Date: 2025-02-24 21:45:49.883634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c469036df7'
down_revision = '8bdf35c902e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('activity_tags',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_tags_activity_id_activity')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_activity_tags_tag_id_tag')),
    sa.PrimaryKeyConstraint('activity_id', 'tag_id', name=op.f('pk_activity_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
