"""Add memo column to Record

Revision ID: 88c3673c06a2
Revises: 1796ff66d4c6
Create Date: 2025-03-08 15:35:18.014520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c3673c06a2'
down_revision = '1796ff66d4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('memo')

    # ### end Alembic commands ###
