"""Drop category table

Revision ID: 8bdf35c902e3
Revises: 9a92da123321
Create Date: 2025-02-24 20:21:55.696160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdf35c902e3'
down_revision = '9a92da123321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_category_id_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_activity_category_id_category', 'category', ['category_id'], ['id'])

    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['activity_group.id'], name='fk_category_group_id_activity_group'),
    sa.PrimaryKeyConstraint('id', name='pk_category')
    )
    # ### end Alembic commands ###
