"""Initial base migration

Revision ID: 8eabb803f8a4
Revises: 
Create Date: 2025-03-16 22:34:34.891878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eabb803f8a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('icon_color', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_group')),
    sa.UniqueConstraint('name', name=op.f('uq_activity_group_name'))
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.Enum('COUNT', 'MINUTES', name='activityunittype'), nullable=True),
    sa.Column('asset_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['activity_group.id'], name=op.f('fk_activity_group_id_activity_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    op.create_table('activity_tags',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_tags_activity_id_activity')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_activity_tags_tag_id_tag')),
    sa.PrimaryKeyConstraint('activity_id', 'tag_id', name=op.f('pk_activity_tags'))
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_record_activity_id_activity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('activity_tags')
    op.drop_table('activity')
    op.drop_table('tag')
    op.drop_table('activity_group')
    # ### end Alembic commands ###
