"""Add position column to ActivityGroup and Category

Revision ID: a15e908b4e22
Revises: 30e481566aec
Create Date: 2025-02-20 20:20:50.315832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15e908b4e22'
down_revision = '30e481566aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('activity_group', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
